### ISSUE TITLE
ValueError: math domain error in genotype quality calculation

### ISSUE THREAD

**Issue by inti** [COMBINE-lab/maximum-likelihood-relatedness-estimation#12]
Hi,

on line 289 of SNPbam2vcf.py
https://github.com/COMBINE-lab/maximum-likelihood-relatedness-estimation/blob/93b8618554cb25b24d813ba07fed9320c55e0636/src_python/SNPbam2vcf/SNPbam2vcf.py#L289

```
GQ=-10*math.log10(10**GL_sort[1]/10**GL_sort[2])
```

I am finding issues with these genotype, printing GL_sort I get `[-1252.6248170198364, -650.5741494345825, -148.3791894556184]` which leads to `math.log10( *0* )` generating the error 

```
Traceback (most recent call last):
  File "src_python/SNPbam2vcf/SNPbam2vcf.py", line 290, in <module>
    GQ=-10*math.log10(10**GL_sort[1]/10**GL_sort[2])
ValueError: math domain error
```

Does it make sense to check for `10**GL_sort[1]/10**GL_sort[2] = 10**(GL_sort[1] - GL_sort[2]) = 0` and set `GQ=0` to avoid the error?

Thanks in advance

**Comment by kveeramah** [comment]
@inti 

We don't want to set GQ to be 0, in fact we want the opposite in this case, as the -650 is so small in comparison to -148, so we are very certain about this genotype.

You should be able to fix the problem by substituting this line instead of the existing line 290:

GQ=(GL_sort[1]-GL_sort[2])*-10

if this works, let me know and i'll change the github version.

**Comment by inti** [comment]
this seems to work fine.

thanks a lot!
